aparelho = input("Qual o seu aparelho?:")
Potencia = float(input("Qual a potencia de seu apreho em W?:"))
horaDia = float(input("Quantas horas por dia esse aparelho é utilizado?:"))
KwH = float(input("Qual o preço do KwH na sua cidade?:"))
KwHmensais = float((Potencia*horaDia*30) / 1000)
gastoMensal = float(KwHmensais*KwH)
print (f"Aparelho:{aparelho}")
print (f"Este aparelho consome {KwHmensais} KwH/mês.")
print (f"Isto gera um custo médio de {gastoMensal:.2f} reais")